// <auto-generated />
using System;
using GeradorCertificadosOnline.Infraestrutura.Compartilhado.Orm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeradorCertificadosOnline.Infraestrutura.Compartilhado.Orm.Migrations
{
    [DbContext(typeof(CertificadosDbContext))]
    [Migration("20260915182222_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeradorCertificadosOnline.Dominio.Modulos.Certificados.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("GeradoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StatusGeracao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId", "StatusGeracao");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("GeradorCertificadosOnline.Dominio.Modulos.Certificados.ProcessamentoCertificados", b =>
                {
                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaminhoZip")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ConcluidoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Falhas")
                        .HasColumnType("int");

                    b.Property<int>("Gerados")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("IniciadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TotalCertificados")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.ToTable("ProcessamentosCertificados", (string)null);
                });

            modelBuilder.Entity("GeradorCertificadosOnline.Dominio.Modulos.Cursos.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataConclusao")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("GeradorCertificadosOnline.Dominio.Modulos.Certificados.Certificado", b =>
                {
                    b.HasOne("GeradorCertificadosOnline.Dominio.Modulos.Cursos.Curso", "Curso")
                        .WithMany("Certificados")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("GeradorCertificadosOnline.Dominio.Modulos.Certificados.ProcessamentoCertificados", b =>
                {
                    b.HasOne("GeradorCertificadosOnline.Dominio.Modulos.Cursos.Curso", "Curso")
                        .WithOne("Processamento")
                        .HasForeignKey("GeradorCertificadosOnline.Dominio.Modulos.Certificados.ProcessamentoCertificados", "CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("GeradorCertificadosOnline.Dominio.Modulos.Cursos.Curso", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("Processamento");
                });
#pragma warning restore 612, 618
        }
    }
}
